name: php-dockernize

services:
  web-php56:
    container_name: php56
    build:
      context: ../
      dockerfile: docker/php56
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ../web-php56/:/var/www/html/

  web-php74:
    container_name: php74
    build:
      context: ../
      dockerfile: docker/php74
    restart: unless-stopped
    ports:
      - 8001:8000
    entrypoint: sh -c "composer install --prefer-dist --no-scripts -q -o && php artisan serve --host=0.0.0.0 --port 8000"
    volumes:
      - ../web-php74/:/app/
      - ../web-php74/storage:/app/storage:rw

  memcached:
    container_name: memcached
    image: memcached:alpine
    restart: unless-stopped
    ports:
      - 11211:11211
